### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by kalmarek** [oscar-system/Polymake.jl#30]
- [x] parser (waiting for the JSON from Polymake) (#29, new one: #119 )
- [x] Exception on the Polymake execution (#48 )
- [x] Methods (#27, #34)
- [x] tab completion (#45 ,#46)
- [x] Build system (via #76)
- [x] `polymake>` REPL mode (#47)
- [x] c++lib independent typenames in PropertyValue  (#38)
- [x] Wrappers for BigObjects (#178)
- [x] Document our wrapper
- [x] Documentation (in an automated way from Polymake):
  - [x] functions (#119)
  - [x] objects: (#178); 
  - [ ] methods (is it even possible???) (#192)
- [ ] Most commonly used SmallObjects:
  - ~[ ] `BitSet`~
  - [x] `IncidenceMatrix` (#184),
  - [x] `SparseVector` (#208)
  - [x] `SparseMatrix` (#181) 
  - [x] `Polynomial`-types? (#216)
  - [x] `TropicalNumber` (#182)
  - [ ] `QuadraticExtension` (#221)
  - ~[ ] `Graph`~
  - ~[ ] `Map*`-types~ 
  - ~[ ] `Pair`~
- [x] solve 0-1 based indexing (is this even a realistic goal? we need to know the intention how the object is going to be used later...) (we have `to_(zero|one)_based_indexing` functions)

**Comment by sebasguts** [comment]
Methods work.
Parser still needs work, but waiting for input from Eugen

**Comment by sebasguts** [comment]
I am going to take care of the build system and the parser.

By wrappers you mean Julia structs that encapsulate different kinds of `pm_perl_Object`?

**Comment by kalmarek** [comment]
yes, the order is not random: if we want to have some meaningful tab completion, we need to make it selective based on the PerlObject/BigObject we complete for.

**Comment by saschatimme** [comment]
After my discussion with Michael, here are the things he suggested we should add:

- [ ] Add a "How to add a new small type" guide
- [ ] Document the functions in `polymake_caller.cpp`
- [ ] Add an explanation for the `static_cast<long>` stuff
- [ ] Write done something regarding the CxxWrap inference problems (everything is just inferred as `Any`)
- [ ] Simplify the plenty of type mappings. An idea of Michael was to have a separate txt file from which we can auto generate these type maps.

**Comment by sebasguts** [comment]
Okay, how should we split this up?

I would guess I am the natural choice for 2. Maybe @saschatimme or @kalmarek can do 1, and @saschatimme should do 3 (because he is the guy with the mac ;)).

**Comment by kalmarek** [comment]
there is also documentation of "getting Polymake.jl going" where we're waiting for a release of polymake with all the necessary changes (3.2.1?)

**Comment by saschatimme** [comment]
Lars is currently preparing a snapshot which will be put on the [polymake github repo](https://github.com/polymake/polymake/tree/Snapshots).

**Comment by kalmarek** [comment]
have a look:
https://gist.github.com/kalmarek/c5a38f733903753a72abedf1dcd63ebb

m
